.TH "src Directory Reference" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBestimation\fP"
.br
.ti -1c
.RI "directory \fBinput\fP"
.br
.ti -1c
.RI "directory \fBmain\fP"
.br
.ti -1c
.RI "directory \fBmodel\fP"
.br
.ti -1c
.RI "directory \fBoptimizer\fP"
.br
.ti -1c
.RI "directory \fBoutput\fP"
.br
.ti -1c
.RI "directory \fBtrace\fP"
.br
.ti -1c
.RI "directory \fBtype\fP"
.br
.ti -1c
.RI "directory \fButil\fP"
.br
.in -1c
