.TH "src/model/parameter Directory Reference" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/model/parameter Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBParameterModel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBParameterModel\&.h\fP"
.br
.ti -1c
.RI "file \fBRaschModel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRaschModel\&.h\fP"
.br
.ti -1c
.RI "file \fBThreePLModel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBThreePLModel\&.h\fP"
.br
.ti -1c
.RI "file \fBTwoPLModel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTwoPLModel\&.h\fP"
.br
.in -1c
