.TH "src/estimation Directory Reference" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/estimation Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbayesian\fP"
.br
.ti -1c
.RI "directory \fBclassical\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBEstimation\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEstimation\&.h\fP"
.br
.in -1c
