.TH "src/model/item Directory Reference" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/model/item Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDichotomousModel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDichotomousModel\&.h\fP"
.br
.ti -1c
.RI "file \fBItemModel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBItemModel\&.h\fP"
.br
.ti -1c
.RI "file \fBPolytomousModel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPolytomousModel\&.h\fP"
.br
.in -1c
