.TH "src/util/asa111.cpp" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/asa111.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include 'asa111\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBN_MAX\fP   17"
.br
.ti -1c
.RI "#define \fBTIME_SIZE\fP   40"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnormal_01_cdf_values\fP (int *n_data, double *x, double *fx)"
.br
.ti -1c
.RI "double \fBppnd\fP (double p, int *ifault)"
.br
.ti -1c
.RI "double \fBr8_abs\fP (double x)"
.br
.ti -1c
.RI "void \fBtimestamp\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define N_MAX   17"

.PP
Referenced by normal_01_cdf_values()\&.
.SS "#define TIME_SIZE   40"

.PP
Referenced by timestamp()\&.
.SH "Function Documentation"
.PP 
.SS "void normal_01_cdf_values (int * n_data, double * x, double * fx)"

.PP
Definition at line 13 of file asa111\&.cpp\&.
.PP
References N_MAX\&.
.SS "double ppnd (double p, int * ifault)"

.PP
Definition at line 132 of file asa111\&.cpp\&.
.PP
References r8_abs()\&.
.PP
Referenced by normalInverse()\&.
.SS "double r8_abs (double x)"

.PP
Definition at line 255 of file asa111\&.cpp\&.
.PP
Referenced by ppnd()\&.
.SS "void timestamp (void)"

.PP
Definition at line 296 of file asa111\&.cpp\&.
.PP
References TIME_SIZE\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
