src/util/asa111.cpp
NAME
src/util/asa111.cpp -
SYNOPSIS
#include <cstdlib>
#include <iostream>
#include <iomanip>
#include <cmath>
#include <ctime>
#include 'asa111.hpp'
Macros
#define N_MAX 17
#define TIME_SIZE 40
Functions
void normal_01_cdf_values (int *n_data, double *x, double *fx)
double ppnd (double p, int *ifault)
double r8_abs (double x)
void timestamp ()
Macro Definition Documentation
#define N_MAX 17
Referenced by normal_01_cdf_values().
#define TIME_SIZE 40
Referenced by timestamp().
Function Documentation
void normal_01_cdf_values (int * n_data, double * x, double * fx)
Definition at line 13 of file asa111.cpp.
References N_MAX.
double ppnd (double p, int * ifault)
Definition at line 132 of file asa111.cpp.
References r8_abs().
Referenced by normalInverse().
double r8_abs (double x)
Definition at line 255 of file asa111.cpp.
Referenced by ppnd().
void timestamp (void)
Definition at line 296 of file asa111.cpp.
References TIME_SIZE.
Author
Generated automatically by Doxygen for SICS IRT from the source code.