.TH "src/estimation/bayesian/BayesianEstimation.h" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/estimation/bayesian/BayesianEstimation.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <estimation/Estimation\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBayesianEstimation\fP"
.br
.RI "\fI\fBEstimation\fP interface for bayesian methods, currently not implemented\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
