.TH "BayesianEstimation" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BayesianEstimation \- \fBEstimation\fP interface for bayesian methods, currently not implemented\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BayesianEstimation\&.h>\fP
.PP
Inherits \fBEstimation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBayesianEstimation\fP ()"
.br
.ti -1c
.RI "void \fBestimate\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBModel\fP *)"
.br
.ti -1c
.RI "virtual \fB~BayesianEstimation\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBEstimation\fP interface for bayesian methods, currently not implemented\&. 
.PP
Definition at line 14 of file BayesianEstimation\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BayesianEstimation::BayesianEstimation ()"

.PP
Definition at line 10 of file BayesianEstimation\&.cpp\&.
.SS "BayesianEstimation::~BayesianEstimation ()\fC [virtual]\fP"

.PP
Definition at line 20 of file BayesianEstimation\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void BayesianEstimation::estimate ()\fC [virtual]\fP"

.PP
Implements \fBEstimation\fP\&.
.PP
Definition at line 14 of file BayesianEstimation\&.cpp\&.
.SS "void BayesianEstimation::setModel (\fBModel\fP * model)\fC [virtual]\fP"

.PP
Implements \fBEstimation\fP\&.
.PP
Definition at line 17 of file BayesianEstimation\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
