.TH "src/optimizer/BFGSOptimizer.h" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/optimizer/BFGSOptimizer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <type/Constant\&.h>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
