src/util/blasInterface.h
NAME
src/util/blasInterface.h -
SYNOPSIS
#include 'type/Matrix.h'
#include <openblas/cblas.h>
#include <openblas/lapacke/lapacke.h>
#include <vector>
Functions
void arrayPrint (double *t, int m)
Functions in this file matrixMultiply : doubles matrixInverse : doubles.
void arrayPrint (long double *t, int m)
int matrixMultiply (Matrix< double > &A, Matrix< double > &B, Matrix< double > &C)
Double general matrix multiplication C = A.B.
int ApproximateMatrixInverse (Matrix< double > &M)
Performs spectral decomposition to approximate a matrix inverse.
Function Documentation
int ApproximateMatrixInverse (Matrix< double > & M) [inline]
Performs spectral decomposition to approximate a matrix inverse.
Definition at line 70 of file blasInterface.h.
References Matrix< T >::copy(), matrixMultiply(), Matrix< T >::memory, Matrix< T >::nC(), Matrix< T >::nR(), and Matrix< T >::reset().
Referenced by pachotest().
void arrayPrint (double * t, int m) [inline]
Functions in this file matrixMultiply : doubles matrixInverse : doubles.
Definition at line 22 of file blasInterface.h.
void arrayPrint (long double * t, int m) [inline]
Definition at line 27 of file blasInterface.h.
int matrixMultiply (Matrix< double > & A, Matrix< double > & B, Matrix< double > & C) [inline]
Double general matrix multiplication C = A.B.
Definition at line 34 of file blasInterface.h.
References Matrix< T >::ld, Matrix< T >::memory, Matrix< T >::nC(), Matrix< T >::nR(), and Matrix< T >::transposed.
Referenced by ApproximateMatrixInverse().
Author
Generated automatically by Doxygen for SICS IRT from the source code.