.TH "src/type/matrix/BlockDiagonalMatrix.cpp" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/type/matrix/BlockDiagonalMatrix.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'BlockDiagonalMatrix\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
