.TH "BlockDiagonalMatrix" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockDiagonalMatrix \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BlockDiagonalMatrix\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockDiagonalMatrix\fP ()"
.br
.ti -1c
.RI "virtual \fB~BlockDiagonalMatrix\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file BlockDiagonalMatrix\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlockDiagonalMatrix::BlockDiagonalMatrix ()"

.PP
Definition at line 10 of file BlockDiagonalMatrix\&.cpp\&.
.SS "BlockDiagonalMatrix::~BlockDiagonalMatrix ()\fC [virtual]\fP"

.PP
Definition at line 15 of file BlockDiagonalMatrix\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
