.TH "src/estimation/classical/ClassicalEstimation.h" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/estimation/classical/ClassicalEstimation.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <estimation/Estimation\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClassicalEstimation\fP"
.br
.RI "\fIClassical estimation class all the classical estimation methods must derive from this class this class is an interface\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
