.TH "src/type/Constant.h" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/type/Constant.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConstant\fP"
.br
.RI "\fIDefines constants used in the SICS library import this class when using a constant TODO : Config file modification for constants\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
