.TH "Constant" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Constant \- Defines constants used in the SICS library import this class when using a constant TODO : Config file modification for constants\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Constant\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static double \fBNORM_CONST\fP = 1"
.br
.ti -1c
.RI "static double \fBMAX_EXP\fP = 35\&.0"
.br
.ti -1c
.RI "static double \fBINFINITE\fP = 1e30"
.br
.ti -1c
.RI "static double \fBEPSILON\fP = 1e-20"
.br
.ti -1c
.RI "static string \fBINITIAL_VALUE_METHOD\fP = 'ANDRADE'"
.br
.ti -1c
.RI "static double \fBstepredn\fP = 0\&.2"
.br
.ti -1c
.RI "static double \fBacctol\fP = 0\&.0001"
.br
.ti -1c
.RI "static double \fBreltest\fP = 10\&.0"
.br
.ti -1c
.RI "static double \fBabstol\fP = 0\&.00001"
.br
.ti -1c
.RI "static double \fBreltol\fP = 1e-8"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines constants used in the SICS library import this class when using a constant TODO : Config file modification for constants\&. 
.PP
Definition at line 19 of file Constant\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double Constant::abstol = 0\&.00001\fC [static]\fP"

.PP
Definition at line 30 of file Constant\&.h\&.
.SS "double Constant::acctol = 0\&.0001\fC [static]\fP"

.PP
Definition at line 28 of file Constant\&.h\&.
.SS "double Constant::EPSILON = 1e-20\fC [static]\fP"

.PP
Definition at line 24 of file Constant\&.h\&.
.SS "double Constant::INFINITE = 1e30\fC [static]\fP"

.PP
Definition at line 23 of file Constant\&.h\&.
.SS "string Constant::INITIAL_VALUE_METHOD = 'ANDRADE'\fC [static]\fP"

.PP
Definition at line 25 of file Constant\&.h\&.
.SS "double Constant::MAX_EXP = 35\&.0\fC [static]\fP"

.PP
Definition at line 22 of file Constant\&.h\&.
.PP
Referenced by ThreePLModel::successProbability()\&.
.SS "double Constant::NORM_CONST = 1\fC [static]\fP"

.PP
Definition at line 21 of file Constant\&.h\&.
.PP
Referenced by ThreePLModel::gradient(), ThreePLModel::Hessian(), and ThreePLModel::successProbability()\&.
.SS "double Constant::reltest = 10\&.0\fC [static]\fP"

.PP
Definition at line 29 of file Constant\&.h\&.
.SS "double Constant::reltol = 1e-8\fC [static]\fP"

.PP
Definition at line 31 of file Constant\&.h\&.
.SS "double Constant::stepredn = 0\&.2\fC [static]\fP"

.PP
Definition at line 27 of file Constant\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
