.TH "DichotomousModel" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DichotomousModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DichotomousModel\&.h>\fP
.PP
Inherits \fBItemModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDichotomousModel\fP ()"
.br
.ti -1c
.RI "int \fBcountCategories\fP ()"
.br
.ti -1c
.RI "int \fBcountItems\fP ()"
.br
.ti -1c
.RI "\fBDataSet\fP * \fBgetDataset\fP ()"
.br
.ti -1c
.RI "void \fBsetDataset\fP (\fBDataSet\fP *dataset)"
.br
.ti -1c
.RI "virtual \fB~DichotomousModel\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file DichotomousModel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DichotomousModel::DichotomousModel ()"

.PP
Definition at line 10 of file DichotomousModel\&.cpp\&.
.SS "DichotomousModel::~DichotomousModel ()\fC [virtual]\fP"

.PP
Definition at line 32 of file DichotomousModel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int DichotomousModel::countCategories ()\fC [virtual]\fP"

.PP
Implements \fBItemModel\fP\&.
.PP
Definition at line 15 of file DichotomousModel\&.cpp\&.
.SS "int DichotomousModel::countItems ()\fC [virtual]\fP"

.PP
Implements \fBItemModel\fP\&.
.PP
Definition at line 27 of file DichotomousModel\&.cpp\&.
.PP
References PatternMatrix::countItems(), and ItemModel::dataSet\&.
.SS "\fBDataSet\fP * DichotomousModel::getDataset ()\fC [virtual]\fP"

.PP
Implements \fBItemModel\fP\&.
.PP
Definition at line 19 of file DichotomousModel\&.cpp\&.
.PP
References ItemModel::dataSet\&.
.SS "void DichotomousModel::setDataset (\fBDataSet\fP * dataset)\fC [virtual]\fP"

.PP
Implements \fBItemModel\fP\&.
.PP
Definition at line 23 of file DichotomousModel\&.cpp\&.
.PP
References ItemModel::dataSet\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
