.TH "src/model/dimension/DimensionModel.h" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/model/dimension/DimensionModel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <type/LatentTraitSet\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDimensionModel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
