DimensionModel
NAME
DimensionModel -
SYNOPSIS
#include <DimensionModel.h>
Inherited by MultidimensionalModel, MultiUniDimModel, and UnidimensionalModel.
Public Member Functions
virtual int getNumDimensions ()=0
virtual vector< int > getDimVector ()=0
virtual LatentTraitSet * getLatentTraitSet () const =0
virtual void setLatentTraitSet (LatentTraitSet *latentTraitSet)=0
virtual ~DimensionModel ()
Protected Attributes
LatentTraitSet * latentTraitSet
Detailed Description
Definition at line 16 of file DimensionModel.h.
Constructor & Destructor Documentation
DimensionModel::~DimensionModel () [virtual]
Definition at line 10 of file DimensionModel.cpp.
Member Function Documentation
virtual vector<int> DimensionModel::getDimVector () [pure virtual]
Implemented in MultidimensionalModel, MultiUniDimModel, and UnidimensionalModel.
virtual LatentTraitSet* DimensionModel::getLatentTraitSet () const [pure virtual]
Implemented in MultidimensionalModel, MultiUniDimModel, and UnidimensionalModel.
Referenced by ThreePLModel::buildParameterSet(), oneRun(), EMEstimation::setModel(), EMEstimation::stepE(), EMEstimation::stepM(), and ThreePLModel::successProbability().
virtual int DimensionModel::getNumDimensions () [pure virtual]
Implemented in MultidimensionalModel, MultiUniDimModel, and UnidimensionalModel.
virtual void DimensionModel::setLatentTraitSet (LatentTraitSet * latentTraitSet) [pure virtual]
Implemented in MultidimensionalModel, MultiUniDimModel, and UnidimensionalModel.
Member Data Documentation
LatentTraitSet* DimensionModel::latentTraitSet [protected]
Definition at line 18 of file DimensionModel.h.
Referenced by UnidimensionalModel::getDimVector(), MultiUniDimModel::getLatentTraitSet(), UnidimensionalModel::getLatentTraitSet(), MultidimensionalModel::getLatentTraitSet(), MultiUniDimModel::setLatentTraitSet(), UnidimensionalModel::setLatentTraitSet(), MultidimensionalModel::setLatentTraitSet(), UnidimensionalModel::UnidimensionalModel(), and UnidimensionalModel::~UnidimensionalModel().
Author
Generated automatically by Doxygen for SICS IRT from the source code.