.TH "DimensionModel" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DimensionModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DimensionModel\&.h>\fP
.PP
Inherited by \fBMultidimensionalModel\fP, \fBMultiUniDimModel\fP, and \fBUnidimensionalModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBgetNumDimensions\fP ()=0"
.br
.ti -1c
.RI "virtual vector< int > \fBgetDimVector\fP ()=0"
.br
.ti -1c
.RI "virtual \fBLatentTraitSet\fP * \fBgetLatentTraitSet\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBsetLatentTraitSet\fP (\fBLatentTraitSet\fP *\fBlatentTraitSet\fP)=0"
.br
.ti -1c
.RI "virtual \fB~DimensionModel\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBLatentTraitSet\fP * \fBlatentTraitSet\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file DimensionModel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DimensionModel::~DimensionModel ()\fC [virtual]\fP"

.PP
Definition at line 10 of file DimensionModel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual vector<int> DimensionModel::getDimVector ()\fC [pure virtual]\fP"

.PP
Implemented in \fBMultidimensionalModel\fP, \fBMultiUniDimModel\fP, and \fBUnidimensionalModel\fP\&.
.SS "virtual \fBLatentTraitSet\fP* DimensionModel::getLatentTraitSet () const\fC [pure virtual]\fP"

.PP
Implemented in \fBMultidimensionalModel\fP, \fBMultiUniDimModel\fP, and \fBUnidimensionalModel\fP\&.
.PP
Referenced by ThreePLModel::buildParameterSet(), oneRun(), EMEstimation::setModel(), EMEstimation::stepE(), EMEstimation::stepM(), and ThreePLModel::successProbability()\&.
.SS "virtual int DimensionModel::getNumDimensions ()\fC [pure virtual]\fP"

.PP
Implemented in \fBMultidimensionalModel\fP, \fBMultiUniDimModel\fP, and \fBUnidimensionalModel\fP\&.
.SS "virtual void DimensionModel::setLatentTraitSet (\fBLatentTraitSet\fP * latentTraitSet)\fC [pure virtual]\fP"

.PP
Implemented in \fBMultidimensionalModel\fP, \fBMultiUniDimModel\fP, and \fBUnidimensionalModel\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLatentTraitSet\fP* DimensionModel::latentTraitSet\fC [protected]\fP"

.PP
Definition at line 18 of file DimensionModel\&.h\&.
.PP
Referenced by UnidimensionalModel::getDimVector(), MultiUniDimModel::getLatentTraitSet(), UnidimensionalModel::getLatentTraitSet(), MultidimensionalModel::getLatentTraitSet(), MultiUniDimModel::setLatentTraitSet(), UnidimensionalModel::setLatentTraitSet(), MultidimensionalModel::setLatentTraitSet(), UnidimensionalModel::UnidimensionalModel(), and UnidimensionalModel::~UnidimensionalModel()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
