.TH "src/estimation/classical/EMEstimation.h" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/estimation/classical/EMEstimation.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <estimation/classical/ClassicalEstimation\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <trace/Trace\&.h>\fP
.br
\fC#include <type/Matrix\&.h>\fP
.br
\fC#include <type/PatternMatrix\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEMEstimation\fP"
.br
.RI "\fIClassical estimation through the EM algorithm, generic for the models however must be called with specific model object, the optimization algorithm can be any from the optimizers class\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
