EMEstimation
NAME
EMEstimation - Classical estimation through the EM algorithm, generic for the models however must be called with specific model object, the optimization algorithm can be any from the optimizers class.
SYNOPSIS
#include <EMEstimation.h>
Inherits ClassicalEstimation.
Public Member Functions
EMEstimation ()
virtual ~EMEstimation ()
void estimate ()
Main loop of the EM estimation orchestrates the parameters for the estimation, and holds the estimation for the iterations.
void stepE ()
Step E of the EM method, this step takes the actual estimation of the parameters, and produces a f and a r matrices used in the maximization step.
void stepM ()
Executes the maximization step using the inputted or default optimizer currently only supporting BFGS and newton algorithms TODO : Relax Convergence criterias.
void setModel (Model *model)
Sets the model to be estimated, currently only supports 3PL model.
void checkRunningConditions ()
Check if all the conditions are met for running the model, can report an error to a logger.
void setOptimizationAlgorithm (string algorithm)
Sets the optimization algorithm.
void setTrace (string filename)
Sets the reporter for the trace.
void setTrace (Trace trace)
void setInitialValues (map< Parameter, Matrix< double > * > parameterSet)
Sets the initial values for the estimation, use this for inputting a matrix as initial values.
void setInitialValues (string method)
Sets the initial values according to a method of calculating the values Possible methods : ANDRADE, OSPINA, RANDOM,.
int getIterations () const
Returns the iterations that took the estimation to obtain an answer.
Private Attributes
Matrix< double > * f
Matrix< double > * r
Trace * logger
Model * model
Optimizer * optim
bool convergenceSignal
int iterations
Additional Inherited Members
Detailed Description
Classical estimation through the EM algorithm, generic for the models however must be called with specific model object, the optimization algorithm can be any from the optimizers class.
EM is a iterative Estimation Maximization algorithm, please check the literature on how it works. EM estimation requires a quadrature for the implementation of the integrals in the expectation step this quadratures can be obtained from R, or using the supplied ones from the SICS binary quadratures ranging from 1 quadrature node to 101 quadrature nodes.
Definition at line 25 of file EMEstimation.h.
Constructor & Destructor Documentation
EMEstimation::EMEstimation ()
Definition at line 10 of file EMEstimation.cpp.
References convergenceSignal, f, iterations, logger, model, optim, and r.
EMEstimation::~EMEstimation () [virtual]
Definition at line 22 of file EMEstimation.cpp.
References f, logger, optim, and r.
Member Function Documentation
void EMEstimation::checkRunningConditions ()
Check if all the conditions are met for running the model, can report an error to a logger.
Definition at line 443 of file EMEstimation.cpp.
void EMEstimation::estimate () [virtual]
Main loop of the EM estimation orchestrates the parameters for the estimation, and holds the estimation for the iterations. TODO : read maxiterations as a input parameter , idea : calculate the max iterations depending on the items TODO : Output last estimation onto the json for recovery in the program.
Implements ClassicalEstimation.
Definition at line 394 of file EMEstimation.cpp.
References a, c, convergenceSignal, ItemModel::countItems(), d, Model::getItemModel(), Model::getParameterModel(), ParameterModel::getParameterSet(), iterations, model, stepE(), and stepM().
Referenced by oneRun().
int EMEstimation::getIterations () const
Returns the iterations that took the estimation to obtain an answer.
Definition at line 458 of file EMEstimation.cpp.
References iterations.
void EMEstimation::setInitialValues (map< Parameter, Matrix< double > * > parameterSet)
Sets the initial values for the estimation, use this for inputting a matrix as initial values.
Definition at line 53 of file EMEstimation.cpp.
References Model::getParameterModel(), model, and ParameterModel::setParameterSet().
void EMEstimation::setInitialValues (string method)
Sets the initial values according to a method of calculating the values Possible methods : ANDRADE, OSPINA, RANDOM,. The default method is OSPINA , this is the fastest method according to the SICS calculations
Definition at line 66 of file EMEstimation.cpp.
void EMEstimation::setModel (Model * model) [virtual]
Sets the model to be estimated, currently only supports 3PL model.
Implements ClassicalEstimation.
Definition at line 39 of file EMEstimation.cpp.
References ItemModel::countItems(), f, Model::getDimensionModel(), Model::getItemModel(), DimensionModel::getLatentTraitSet(), LatentTraitSet::getTheta(), model, Matrix< T >::nC(), and r.
Referenced by oneRun().
void EMEstimation::setOptimizationAlgorithm (string algorithm)
Sets the optimization algorithm.
Definition at line 447 of file EMEstimation.cpp.
void EMEstimation::setTrace (string filename)
Sets the reporter for the trace.
Definition at line 451 of file EMEstimation.cpp.
void EMEstimation::setTrace (Trace trace)
Definition at line 454 of file EMEstimation.cpp.
void EMEstimation::stepE ()
Step E of the EM method, this step takes the actual estimation of the parameters, and produces a f and a r matrices used in the maximization step. TODO : PARALLELIZABLE FOR
Definition at line 84 of file EMEstimation.cpp.
References a, c, PatternMatrix::checkEnd(), PatternMatrix::countItems(), d, f, PatternMatrix::getCurrentBitSet(), PatternMatrix::getCurrentFrequency(), ItemModel::getDataset(), Model::getDimensionModel(), Model::getItemModel(), DimensionModel::getLatentTraitSet(), Model::getParameterModel(), ParameterModel::getParameterSet(), ParameterModel::getProbability(), LatentTraitSet::getTheta(), LatentTraitSet::getWeight(), PatternMatrix::iterate(), model, Matrix< T >::nC(), r, Matrix< T >::reset(), PatternMatrix::resetIterator(), and Model::successProbability().
Referenced by estimate().
void EMEstimation::stepM ()
Executes the maximization step using the inputted or default optimizer currently only supporting BFGS and newton algorithms TODO : Relax Convergence criterias.
Definition at line 182 of file EMEstimation.cpp.
References a, c, convergenceSignal, DataSet::countItems(), d, ItemModel::getDataset(), Model::getDimensionModel(), Model::getItemModel(), DimensionModel::getLatentTraitSet(), Model::getParameterModel(), ParameterModel::getParameterSet(), LatentTraitSet::getTheta(), ThreePLModel::gradient(), ThreePLModel::Hessian(), ThreePLModel::itemgradient(), ThreePLModel::itemHessian(), ThreePLModel::logLikelihood(), model, Matrix< T >::nC(), optim, Optimizer::searchOptimal(), and ParameterModel::setParameterSet().
Referenced by estimate().
Member Data Documentation
bool EMEstimation::convergenceSignal [private]
Definition at line 72 of file EMEstimation.h.
Referenced by EMEstimation(), estimate(), and stepM().
Matrix<double>* EMEstimation::f [private]
Definition at line 63 of file EMEstimation.h.
Referenced by EMEstimation(), setModel(), stepE(), and ~EMEstimation().
int EMEstimation::iterations [private]
Definition at line 74 of file EMEstimation.h.
Referenced by EMEstimation(), estimate(), and getIterations().
Trace* EMEstimation::logger [private]
Definition at line 66 of file EMEstimation.h.
Referenced by EMEstimation(), and ~EMEstimation().
Model* EMEstimation::model [private]
Definition at line 68 of file EMEstimation.h.
Referenced by EMEstimation(), estimate(), setInitialValues(), setModel(), stepE(), and stepM().
Optimizer* EMEstimation::optim [private]
Definition at line 70 of file EMEstimation.h.
Referenced by EMEstimation(), stepM(), and ~EMEstimation().
Matrix<double>* EMEstimation::r [private]
Definition at line 64 of file EMEstimation.h.
Referenced by EMEstimation(), setModel(), stepE(), and ~EMEstimation().
Author
Generated automatically by Doxygen for SICS IRT from the source code.