.TH "src/estimation/Estimation.h" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/estimation/Estimation.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <model/Model\&.h>\fP
.br
\fC#include <type/Matrix\&.h>\fP
.br
\fC#include <optimizer/Optimizer\&.h>\fP
.br
\fC#include <model/parameter/ThreePLModel\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEstimation\fP"
.br
.RI "\fIParent estimation interface for all estimation methods\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
