.TH "Estimation" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Estimation \- Parent estimation interface for all estimation methods\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Estimation\&.h>\fP
.PP
Inherited by \fBBayesianEstimation\fP, and \fBClassicalEstimation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBestimate\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBsetModel\fP (\fBModel\fP *)=0"
.br
.ti -1c
.RI "virtual \fB~Estimation\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBModel\fP * \fBmodel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parent estimation interface for all estimation methods\&. 
.PP
Definition at line 19 of file Estimation\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Estimation::~Estimation ()\fC [virtual]\fP"

.PP
Definition at line 10 of file Estimation\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Estimation::estimate ()\fC [pure virtual]\fP"

.PP
Implemented in \fBEMEstimation\fP, \fBClassicalEstimation\fP, and \fBBayesianEstimation\fP\&.
.SS "virtual void Estimation::setModel (\fBModel\fP *)\fC [pure virtual]\fP"

.PP
Implemented in \fBEMEstimation\fP, \fBClassicalEstimation\fP, and \fBBayesianEstimation\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBModel\fP* Estimation::model\fC [protected]\fP"

.PP
Definition at line 21 of file Estimation\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
