.TH "Expectation" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Expectation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Expectation\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpectation\fP ()"
.br
.ti -1c
.RI "virtual \fB~Expectation\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file Expectation\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Expectation::Expectation ()"

.PP
Definition at line 10 of file Expectation\&.cpp\&.
.SS "Expectation::~Expectation ()\fC [virtual]\fP"

.PP
Definition at line 15 of file Expectation\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
