.TH "FisherScoringOptimizer" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FisherScoringOptimizer \- Skeleton for implementing the Fisher \fBOptimizer\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FisherScoringOptimizer\&.h>\fP
.SH "Detailed Description"
.PP 
Skeleton for implementing the Fisher \fBOptimizer\fP\&. 
.PP
Definition at line 13 of file FisherScoringOptimizer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
