Input
NAME
Input - Class that is in charge of taking OS files, streams and other sources for inputting data into the software suite.
SYNOPSIS
#include <Input.h>
Public Member Functions
Input ()
virtual ~Input ()
bool importCSV (char *, PatternMatrix &, unsigned int, unsigned int)
bool importCSV (char *, Matrix< double > &, unsigned int, unsigned int)
Imports binary matrices from a csv.
char getDel () const
Imports generic type matrices from a csv.
void setDel (char)
Gets the delimitier used for inputting.
Private Attributes
char del
Detailed Description
Class that is in charge of taking OS files, streams and other sources for inputting data into the software suite.
Definition at line 28 of file Input.h.
Constructor & Destructor Documentation
Input::Input ()
Definition at line 10 of file Input.cpp.
References del.
Input::~Input () [virtual]
Definition at line 15 of file Input.cpp.
Member Function Documentation
char Input::getDel () const
Imports generic type matrices from a csv.
Definition at line 169 of file Input.cpp.
References del.
bool Input::importCSV (char * filename, PatternMatrix & M, unsigned int rowIdx, unsigned int colIdx)
Definition at line 85 of file Input.cpp.
References del, and PatternMatrix::push().
Referenced by oneRun(), and pachotest().
bool Input::importCSV (char * filename, Matrix< double > & M, unsigned int rowIdx, unsigned int colIdx)
Imports binary matrices from a csv.
Definition at line 18 of file Input.cpp.
References del.
void Input::setDel (char del)
Gets the delimitier used for inputting.
Definition at line 173 of file Input.cpp.
References del.
Member Data Documentation
char Input::del [private]
Definition at line 34 of file Input.h.
Referenced by getDel(), importCSV(), Input(), and setDel().
Author
Generated automatically by Doxygen for SICS IRT from the source code.