.TH "src/input/Input.h" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/input/Input.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <type/PatternMatrix\&.h>\fP
.br
\fC#include <type/Matrix\&.h>\fP
.br
\fC#include <trace/Trace\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInput\fP"
.br
.RI "\fIClass that is in charge of taking OS files, streams and other sources for inputting data into the software suite\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
