ItemModel
NAME
ItemModel -
SYNOPSIS
#include <ItemModel.h>
Inherited by DichotomousModel, and PolytomousModel.
Public Member Functions
virtual int countCategories ()=0
virtual int countItems ()=0
virtual DataSet * getDataset ()=0
virtual void setDataset (DataSet *dataset)=0
virtual ~ItemModel ()
Protected Attributes
DataSet * dataSet
Detailed Description
Definition at line 13 of file ItemModel.h.
Constructor & Destructor Documentation
ItemModel::~ItemModel () [virtual]
Definition at line 11 of file ItemModel.cpp.
Member Function Documentation
virtual int ItemModel::countCategories () [pure virtual]
Implemented in DichotomousModel, and PolytomousModel.
virtual int ItemModel::countItems () [pure virtual]
Implemented in DichotomousModel, and PolytomousModel.
Referenced by ThreePLModel::buildParameterSet(), EMEstimation::estimate(), oneRun(), and EMEstimation::setModel().
virtual DataSet* ItemModel::getDataset () [pure virtual]
Implemented in DichotomousModel, and PolytomousModel.
Referenced by EMEstimation::setInitialValues(), EMEstimation::stepE(), and EMEstimation::stepM().
virtual void ItemModel::setDataset (DataSet * dataset) [pure virtual]
Implemented in DichotomousModel, and PolytomousModel.
Referenced by oneRun().
Member Data Documentation
DataSet* ItemModel::dataSet [protected]
Definition at line 15 of file ItemModel.h.
Referenced by DichotomousModel::countItems(), PolytomousModel::getDataset(), DichotomousModel::getDataset(), PolytomousModel::setDataset(), and DichotomousModel::setDataset().
Author
Generated automatically by Doxygen for SICS IRT from the source code.