.TH "src/model/item/ItemModel.cpp" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/model/item/ItemModel.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <model/item/ItemModel\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
