.TH "src/type/LatentTraitSet.h" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/type/LatentTraitSet.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <type/Matrix\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLatentTraitSet\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
