LatentTraitSet
NAME
LatentTraitSet -
SYNOPSIS
#include <LatentTraitSet.h>
Public Member Functions
LatentTraitSet ()
Matrix< double > * getTheta ()
void setTheta (Matrix< double > *theta)
Matrix< double > * getWeight ()
void setWeight (Matrix< double > *weight)
virtual ~LatentTraitSet ()
Private Attributes
Matrix< double > * theta
Matrix< double > * weight
Detailed Description
Definition at line 13 of file LatentTraitSet.h.
Constructor & Destructor Documentation
LatentTraitSet::LatentTraitSet ()
Definition at line 10 of file LatentTraitSet.cpp.
References theta, and weight.
LatentTraitSet::~LatentTraitSet () [virtual]
Definition at line 31 of file LatentTraitSet.cpp.
References theta, and weight.
Member Function Documentation
Matrix< double > * LatentTraitSet::getTheta ()
Definition at line 15 of file LatentTraitSet.cpp.
References theta.
Referenced by ThreePLModel::buildParameterSet(), UnidimensionalModel::getDimVector(), EMEstimation::setModel(), EMEstimation::stepE(), EMEstimation::stepM(), and ThreePLModel::successProbability().
Matrix< double > * LatentTraitSet::getWeight ()
Definition at line 23 of file LatentTraitSet.cpp.
References weight.
Referenced by EMEstimation::stepE().
void LatentTraitSet::setTheta (Matrix< double > * theta)
Definition at line 19 of file LatentTraitSet.cpp.
References theta.
Referenced by oneRun().
void LatentTraitSet::setWeight (Matrix< double > * weight)
Definition at line 27 of file LatentTraitSet.cpp.
References weight.
Referenced by oneRun().
Member Data Documentation
Matrix<double>* LatentTraitSet::theta [private]
Definition at line 14 of file LatentTraitSet.h.
Referenced by getTheta(), LatentTraitSet(), setTheta(), and ~LatentTraitSet().
Matrix<double>* LatentTraitSet::weight [private]
Definition at line 15 of file LatentTraitSet.h.
Referenced by getWeight(), LatentTraitSet(), setWeight(), and ~LatentTraitSet().
Author
Generated automatically by Doxygen for SICS IRT from the source code.