.TH "src/main/Main.cpp" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/Main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Main\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBbanana\fP (double *args, double *pars, int nargs, int npars)"
.br
.ti -1c
.RI "void \fBbananaGradient\fP (double *args, double *pars, int nargs, int npars, double *\fBgradient\fP)"
.br
.ti -1c
.RI "void \fBrosenbrockTest\fP ()"
.br
.ti -1c
.RI "void \fBpachotest\fP ()"
.br
.ti -1c
.RI "void \fBinitTests\fP (char *filename)"
.br
.ti -1c
.RI "void \fBoneRun\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double banana (double * args, double * pars, int nargs, int npars)"

.PP
Definition at line 14 of file Main\&.cpp\&.
.PP
Referenced by bananaGradient(), and rosenbrockTest()\&.
.SS "void bananaGradient (double * args, double * pars, int nargs, int npars, double * gradient)"

.PP
Definition at line 21 of file Main\&.cpp\&.
.PP
References banana()\&.
.PP
Referenced by rosenbrockTest()\&.
.SS "void initTests (char * filename)"

.PP
Definition at line 76 of file Main\&.cpp\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 140 of file Main\&.cpp\&.
.PP
References oneRun()\&.
.SS "void oneRun ()"

.PP
Definition at line 84 of file Main\&.cpp\&.
.PP
References ParameterModel::buildParameterSet(), ItemModel::countItems(), EMEstimation::estimate(), Model::getDimensionModel(), Model::getItemModel(), DimensionModel::getLatentTraitSet(), Model::getParameterModel(), Input::importCSV(), Matrix< T >::nR(), ItemModel::setDataset(), EMEstimation::setInitialValues(), Model::setModel(), EMEstimation::setModel(), LatentTraitSet::setTheta(), and LatentTraitSet::setWeight()\&.
.PP
Referenced by main()\&.
.SS "void pachotest ()"

.PP
Definition at line 69 of file Main\&.cpp\&.
.PP
References ApproximateMatrixInverse(), and Input::importCSV()\&.
.SS "void rosenbrockTest ()"

.PP
Definition at line 33 of file Main\&.cpp\&.
.PP
References banana(), bananaGradient(), gradient(), and Optimizer::searchOptimal()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
