src/main/Main.cpp
NAME
src/main/Main.cpp -
SYNOPSIS
#include 'Main.h'
Functions
double banana (double *args, double *pars, int nargs, int npars)
void bananaGradient (double *args, double *pars, int nargs, int npars, double *gradient)
void rosenbrockTest ()
void pachotest ()
void initTests (char *filename)
void oneRun ()
int main (int argc, char *argv[])
Function Documentation
double banana (double * args, double * pars, int nargs, int npars)
Definition at line 14 of file Main.cpp.
Referenced by bananaGradient(), and rosenbrockTest().
void bananaGradient (double * args, double * pars, int nargs, int npars, double * gradient)
Definition at line 21 of file Main.cpp.
References banana().
Referenced by rosenbrockTest().
void initTests (char * filename)
Definition at line 76 of file Main.cpp.
int main (int argc, char * argv[])
Definition at line 140 of file Main.cpp.
References oneRun().
void oneRun ()
Definition at line 84 of file Main.cpp.
References ParameterModel::buildParameterSet(), ItemModel::countItems(), EMEstimation::estimate(), Model::getDimensionModel(), Model::getItemModel(), DimensionModel::getLatentTraitSet(), Model::getParameterModel(), Input::importCSV(), Matrix< T >::nR(), ItemModel::setDataset(), EMEstimation::setInitialValues(), Model::setModel(), EMEstimation::setModel(), LatentTraitSet::setTheta(), and LatentTraitSet::setWeight().
Referenced by main().
void pachotest ()
Definition at line 69 of file Main.cpp.
References ApproximateMatrixInverse(), and Input::importCSV().
void rosenbrockTest ()
Definition at line 33 of file Main.cpp.
References banana(), bananaGradient(), gradient(), and Optimizer::searchOptimal().
Author
Generated automatically by Doxygen for SICS IRT from the source code.