.TH "src/main/Main.h" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/Main.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <type/Matrix\&.h>\fP
.br
\fC#include <boost/dynamic_bitset\&.hpp>\fP
.br
\fC#include <type/PatternMatrix\&.h>\fP
.br
\fC#include <model/Model\&.h>\fP
.br
\fC#include <model/ModelFactory\&.h>\fP
.br
\fC#include <model/SICSGeneralModel\&.h>\fP
.br
\fC#include <estimation/classical/EMEstimation\&.h>\fP
.br
\fC#include <input/Input\&.h>\fP
.br
\fC#include <util/NCM\&.h>\fP
.br
\fC#include 'util/blasInterface\&.h'\fP
.br
\fC#include <\&.\&./test/EMTest\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
