Matrix< T >
NAME
Matrix< T > - Supports the Matrix Structures, with indexing on any type, has special operations for general matrix use, is the class used by all the BLAS interface methods , please use this class in the package whenever posible.
SYNOPSIS
#include <Matrix.h>
Public Member Functions
Matrix ()
Matrix (int, int)
Empty object.
Matrix (Matrix< T > &)
Two dimensional Matrix Constructor allocates memory.
Matrix (char I, int size)
Copy constructor.
void reset ()
Create special kinds of matrices (dense identity)
void transpose ()
Reset method, puts all entries in zeros.
void copy (Matrix< T > &)
Transposes the matrix, notice it does not perform memory transpose, only index transpose.
T getDeterminant ()
Copy constructor.
int nR ()
Outputs the determinant of the matrix.
int nC ()
Returns number of rows.
T sum ()
Returns number of columns.
T & operator() (const int nCol, const int nRow)
Returns the sum of all objects.
T & operator() (const int element)
Accessing operator for a element.
bool isSymmetric () const
Output operator.
void setSymmetric (bool symmetric)
Symmetry flag for optimizations.
virtual ~Matrix ()
Set to true the symmetry flag.
Public Attributes
bool transposed
bool symmetric
T * memory
int ld
Static Public Attributes
static char del = ' '
Private Member Functions
T m (char)
T get3x3determinant ()
Private Attributes
int nCol
int nRow
Friends
ostream & operator (ostream &, Matrix< T > &)
Accessing operator for a element.
Detailed Description
template<class T>class Matrix< T >
Supports the Matrix Structures, with indexing on any type, has special operations for general matrix use, is the class used by all the BLAS interface methods , please use this class in the package whenever posible.
the class is a templated class supporting any type for components of the matrix, the support of this class is made for two dimension matrices and one dimension vectors, overloaded operators are the parenthesis for one or two dimensional indexing, and the output operator, the class also supports transposed and symmetric matrices and when declaring matrices they can be declared either empty, reseted to a value, as an identity, or as a random matrix. Some very fast methods are implemented for specific matrix sizes. Use this with care.
Definition at line 31 of file Matrix.h.
Constructor & Destructor Documentation
template<class T > Matrix< T >::Matrix ()
Definition at line 102 of file Matrix.h.
template<class T > Matrix< T >::Matrix (int r, int c)
Empty object.
Definition at line 118 of file Matrix.h.
References c.
template<class T> Matrix< T >::Matrix (Matrix< T > & a)
Two dimensional Matrix Constructor allocates memory.
Definition at line 112 of file Matrix.h.
template<class T> Matrix< T >::Matrix (char I, int size)
Copy constructor.
Definition at line 128 of file Matrix.h.
References c.
template<class T > Matrix< T >::~Matrix () [virtual]
Set to true the symmetry flag.
Definition at line 175 of file Matrix.h.
Member Function Documentation
template<class T> void Matrix< T >::copy (Matrix< T > & a)
Transposes the matrix, notice it does not perform memory transpose, only index transpose.
Definition at line 193 of file Matrix.h.
References Matrix< T >::memory, Matrix< T >::nC(), Matrix< T >::nR(), Matrix< T >::symmetric, and Matrix< T >::transposed.
Referenced by ApproximateMatrixInverse().
template<class T > T Matrix< T >::get3x3determinant () [private]
Definition at line 215 of file Matrix.h.
template<class T > T Matrix< T >::getDeterminant ()
Copy constructor.
Definition at line 204 of file Matrix.h.
template<class T > bool Matrix< T >::isSymmetric () const [inline]
Output operator.
Definition at line 165 of file Matrix.h.
template<class T > T Matrix< T >::m (char c) [private]
Definition at line 76 of file Matrix.h.
template<class T > int Matrix< T >::nC ()
Returns number of rows.
Definition at line 97 of file Matrix.h.
Referenced by ApproximateMatrixInverse(), ThreePLModel::buildParameterSet(), Matrix< T >::copy(), UnidimensionalModel::getDimVector(), matrixMultiply(), NCM(), EMEstimation::setModel(), EMEstimation::stepE(), EMEstimation::stepM(), and ThreePLModel::successProbability().
template<class T > int Matrix< T >::nR ()
Outputs the determinant of the matrix.
Definition at line 92 of file Matrix.h.
Referenced by ApproximateMatrixInverse(), Matrix< T >::copy(), matrixMultiply(), NCM(), and oneRun().
template<class T > T & Matrix< T >::operator() (const int nCol, const int nRow)
Returns the sum of all objects.
Definition at line 150 of file Matrix.h.
template<class T > T & Matrix< T >::operator() (const int element)
Accessing operator for a element.
Definition at line 160 of file Matrix.h.
template<class T > void Matrix< T >::reset ()
Create special kinds of matrices (dense identity)
Definition at line 182 of file Matrix.h.
Referenced by ApproximateMatrixInverse(), and EMEstimation::stepE().
template<class T > void Matrix< T >::setSymmetric (bool symmetric) [inline]
Symmetry flag for optimizations.
Definition at line 170 of file Matrix.h.
template<class T > T Matrix< T >::sum ()
Returns number of columns.
Definition at line 81 of file Matrix.h.
template<class T > void Matrix< T >::transpose ()
Reset method, puts all entries in zeros.
Definition at line 187 of file Matrix.h.
Friends And Related Function Documentation
template<class T> ostream& operator (ostream &, Matrix< T > &) [friend]
Accessing operator for a element.
Member Data Documentation
template<class T> char Matrix< T >::del = ' ' [static]
Definition at line 52 of file Matrix.h.
template<class T> int Matrix< T >::ld
Definition at line 51 of file Matrix.h.
Referenced by matrixMultiply().
template<class T> T* Matrix< T >::memory
Definition at line 50 of file Matrix.h.
Referenced by ApproximateMatrixInverse(), Matrix< T >::copy(), and matrixMultiply().
template<class T> int Matrix< T >::nCol [private]
Definition at line 43 of file Matrix.h.
template<class T> int Matrix< T >::nRow [private]
Definition at line 44 of file Matrix.h.
template<class T> bool Matrix< T >::symmetric
Definition at line 49 of file Matrix.h.
Referenced by Matrix< T >::copy().
template<class T> bool Matrix< T >::transposed
Definition at line 48 of file Matrix.h.
Referenced by Matrix< T >::copy(), and matrixMultiply().
Author
Generated automatically by Doxygen for SICS IRT from the source code.