.TH "matrix" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NCM\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double * \fBentries\fP"
.br
.ti -1c
.RI "int \fBrows\fP"
.br
.ti -1c
.RI "int \fBcolumns\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 63 of file NCM\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int matrix::columns"

.PP
Definition at line 67 of file NCM\&.h\&.
.PP
Referenced by Correlation_Newton(), gradient(), Jacobian_matrix(), NCM(), omega_mat(), pre_cg(), precond_matrix(), and printMatrix()\&.
.SS "double* matrix::entries"

.PP
Definition at line 65 of file NCM\&.h\&.
.PP
Referenced by Correlation_Newton(), gradient(), Jacobian_matrix(), NCM(), omega_mat(), pre_cg(), precond_matrix(), and printMatrix()\&.
.SS "int matrix::rows"

.PP
Definition at line 66 of file NCM\&.h\&.
.PP
Referenced by Correlation_Newton(), gradient(), Jacobian_matrix(), NCM(), omega_mat(), pre_cg(), precond_matrix(), and printMatrix()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
