.TH "Model" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model \- \fBModel\fP class that holds the structures for the IRT models can vary across parameters, items and dimensions includes suport for dichotomic and polytomic models multidimensional and singledimensional models future suport for multiscale and longitudinal models can be implemented\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Model\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModel\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBModelFactory\fP *)"
.br
.ti -1c
.RI "void \fBsuccessProbability\fP ()"
.br
.ti -1c
.RI "void \fBbuildParameterSet\fP ()"
.br
.ti -1c
.RI "\fBDimensionModel\fP * \fBgetDimensionModel\fP ()"
.br
.ti -1c
.RI "void \fBsetDimensionModel\fP (\fBDimensionModel\fP *\fBdimensionModel\fP)"
.br
.ti -1c
.RI "\fBItemModel\fP * \fBgetItemModel\fP ()"
.br
.ti -1c
.RI "void \fBsetItemModel\fP (\fBItemModel\fP *\fBitemModel\fP)"
.br
.ti -1c
.RI "\fBParameterModel\fP * \fBgetParameterModel\fP ()"
.br
.ti -1c
.RI "void \fBsetParameterModel\fP (\fBParameterModel\fP *\fBparameterModel\fP)"
.br
.ti -1c
.RI "virtual \fB~Model\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBParameterModel\fP * \fBparameterModel\fP"
.br
.ti -1c
.RI "\fBItemModel\fP * \fBitemModel\fP"
.br
.ti -1c
.RI "\fBDimensionModel\fP * \fBdimensionModel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBModel\fP class that holds the structures for the IRT models can vary across parameters, items and dimensions includes suport for dichotomic and polytomic models multidimensional and singledimensional models future suport for multiscale and longitudinal models can be implemented\&. 
.PP
Definition at line 22 of file Model\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Model::Model ()"

.PP
Definition at line 10 of file Model\&.cpp\&.
.PP
References dimensionModel, itemModel, and parameterModel\&.
.SS "Model::~Model ()\fC [virtual]\fP"

.PP
Definition at line 22 of file Model\&.cpp\&.
.PP
References dimensionModel, itemModel, and parameterModel\&.
.SH "Member Function Documentation"
.PP 
.SS "void Model::buildParameterSet ()"

.PP
Definition at line 55 of file Model\&.cpp\&.
.PP
References ParameterModel::buildParameterSet(), dimensionModel, itemModel, and parameterModel\&.
.SS "\fBDimensionModel\fP * Model::getDimensionModel ()"

.PP
Definition at line 27 of file Model\&.cpp\&.
.PP
References dimensionModel\&.
.PP
Referenced by oneRun(), EMEstimation::setModel(), EMEstimation::stepE(), and EMEstimation::stepM()\&.
.SS "\fBItemModel\fP * Model::getItemModel ()"

.PP
Definition at line 35 of file Model\&.cpp\&.
.PP
References itemModel\&.
.PP
Referenced by EMEstimation::estimate(), oneRun(), EMEstimation::setModel(), EMEstimation::stepE(), and EMEstimation::stepM()\&.
.SS "\fBParameterModel\fP * Model::getParameterModel ()"

.PP
Definition at line 43 of file Model\&.cpp\&.
.PP
References parameterModel\&.
.PP
Referenced by EMEstimation::estimate(), oneRun(), EMEstimation::setInitialValues(), EMEstimation::stepE(), and EMEstimation::stepM()\&.
.SS "void Model::setDimensionModel (\fBDimensionModel\fP * dimensionModel)"

.PP
Definition at line 31 of file Model\&.cpp\&.
.PP
References dimensionModel\&.
.SS "void Model::setItemModel (\fBItemModel\fP * itemModel)"

.PP
Definition at line 39 of file Model\&.cpp\&.
.PP
References itemModel\&.
.SS "void Model::setModel (\fBModelFactory\fP * modelFactory)"

.PP
Definition at line 16 of file Model\&.cpp\&.
.PP
References ModelFactory::createDimensionModel(), ModelFactory::createItemModel(), ModelFactory::createParameterModel(), dimensionModel, itemModel, and parameterModel\&.
.PP
Referenced by oneRun()\&.
.SS "void Model::setParameterModel (\fBParameterModel\fP * parameterModel)"

.PP
Definition at line 47 of file Model\&.cpp\&.
.PP
References parameterModel\&.
.SS "void Model::successProbability ()"

.PP
Definition at line 51 of file Model\&.cpp\&.
.PP
References dimensionModel, parameterModel, and ParameterModel::successProbability()\&.
.PP
Referenced by EMEstimation::stepE()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDimensionModel\fP* Model::dimensionModel\fC [private]\fP"

.PP
Definition at line 25 of file Model\&.h\&.
.PP
Referenced by buildParameterSet(), getDimensionModel(), Model(), setDimensionModel(), setModel(), successProbability(), and ~Model()\&.
.SS "\fBItemModel\fP* Model::itemModel\fC [private]\fP"

.PP
Definition at line 24 of file Model\&.h\&.
.PP
Referenced by buildParameterSet(), getItemModel(), Model(), setItemModel(), setModel(), and ~Model()\&.
.SS "\fBParameterModel\fP* Model::parameterModel\fC [private]\fP"

.PP
Definition at line 23 of file Model\&.h\&.
.PP
Referenced by buildParameterSet(), getParameterModel(), Model(), setModel(), setParameterModel(), successProbability(), and ~Model()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
