.TH "src/model/Model.h" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/model/Model.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <model/parameter/ParameterModel\&.h>\fP
.br
\fC#include <model/item/ItemModel\&.h>\fP
.br
\fC#include <model/dimension/DimensionModel\&.h>\fP
.br
\fC#include <model/ModelFactory\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBModel\fP"
.br
.RI "\fI\fBModel\fP class that holds the structures for the IRT models can vary across parameters, items and dimensions includes suport for dichotomic and polytomic models multidimensional and singledimensional models future suport for multiscale and longitudinal models can be implemented\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
