ModelFactory
NAME
ModelFactory -
SYNOPSIS
#include <ModelFactory.h>
Inherited by SICSGeneralModel.
Public Member Functions
ModelFactory ()
virtual ParameterModel * createParameterModel ()=0
virtual ItemModel * createItemModel ()=0
virtual DimensionModel * createDimensionModel ()=0
virtual ~ModelFactory ()
Detailed Description
Definition at line 15 of file ModelFactory.h.
Constructor & Destructor Documentation
ModelFactory::ModelFactory ()
Definition at line 10 of file ModelFactory.cpp.
ModelFactory::~ModelFactory () [virtual]
Definition at line 15 of file ModelFactory.cpp.
Member Function Documentation
virtual DimensionModel* ModelFactory::createDimensionModel () [pure virtual]
Implemented in SICSGeneralModel.
Referenced by Model::setModel().
virtual ItemModel* ModelFactory::createItemModel () [pure virtual]
Implemented in SICSGeneralModel.
Referenced by Model::setModel().
virtual ParameterModel* ModelFactory::createParameterModel () [pure virtual]
Implemented in SICSGeneralModel.
Referenced by Model::setModel().
Author
Generated automatically by Doxygen for SICS IRT from the source code.