Model
NAME
Model - Model class that holds the structures for the IRT models can vary across parameters, items and dimensions includes suport for dichotomic and polytomic models multidimensional and singledimensional models future suport for multiscale and longitudinal models can be implemented.
SYNOPSIS
#include <Model.h>
Public Member Functions
Model ()
void setModel (ModelFactory *)
void successProbability ()
void buildParameterSet ()
DimensionModel * getDimensionModel ()
void setDimensionModel (DimensionModel *dimensionModel)
ItemModel * getItemModel ()
void setItemModel (ItemModel *itemModel)
ParameterModel * getParameterModel ()
void setParameterModel (ParameterModel *parameterModel)
virtual ~Model ()
Private Attributes
ParameterModel * parameterModel
ItemModel * itemModel
DimensionModel * dimensionModel
Detailed Description
Model class that holds the structures for the IRT models can vary across parameters, items and dimensions includes suport for dichotomic and polytomic models multidimensional and singledimensional models future suport for multiscale and longitudinal models can be implemented.
Definition at line 22 of file Model.h.
Constructor & Destructor Documentation
Model::Model ()
Definition at line 10 of file Model.cpp.
References dimensionModel, itemModel, and parameterModel.
Model::~Model () [virtual]
Definition at line 22 of file Model.cpp.
References dimensionModel, itemModel, and parameterModel.
Member Function Documentation
void Model::buildParameterSet ()
Definition at line 55 of file Model.cpp.
References ParameterModel::buildParameterSet(), dimensionModel, itemModel, and parameterModel.
DimensionModel * Model::getDimensionModel ()
Definition at line 27 of file Model.cpp.
References dimensionModel.
Referenced by oneRun(), EMEstimation::setModel(), EMEstimation::stepE(), and EMEstimation::stepM().
ItemModel * Model::getItemModel ()
Definition at line 35 of file Model.cpp.
References itemModel.
Referenced by EMEstimation::estimate(), oneRun(), EMEstimation::setModel(), EMEstimation::stepE(), and EMEstimation::stepM().
ParameterModel * Model::getParameterModel ()
Definition at line 43 of file Model.cpp.
References parameterModel.
Referenced by EMEstimation::estimate(), oneRun(), EMEstimation::setInitialValues(), EMEstimation::stepE(), and EMEstimation::stepM().
void Model::setDimensionModel (DimensionModel * dimensionModel)
Definition at line 31 of file Model.cpp.
References dimensionModel.
void Model::setItemModel (ItemModel * itemModel)
Definition at line 39 of file Model.cpp.
References itemModel.
void Model::setModel (ModelFactory * modelFactory)
Definition at line 16 of file Model.cpp.
References ModelFactory::createDimensionModel(), ModelFactory::createItemModel(), ModelFactory::createParameterModel(), dimensionModel, itemModel, and parameterModel.
Referenced by oneRun().
void Model::setParameterModel (ParameterModel * parameterModel)
Definition at line 47 of file Model.cpp.
References parameterModel.
void Model::successProbability ()
Definition at line 51 of file Model.cpp.
References dimensionModel, parameterModel, and ParameterModel::successProbability().
Referenced by EMEstimation::stepE().
Member Data Documentation
DimensionModel* Model::dimensionModel [private]
Definition at line 25 of file Model.h.
Referenced by buildParameterSet(), getDimensionModel(), Model(), setDimensionModel(), setModel(), successProbability(), and ~Model().
ItemModel* Model::itemModel [private]
Definition at line 24 of file Model.h.
Referenced by buildParameterSet(), getItemModel(), Model(), setItemModel(), setModel(), and ~Model().
ParameterModel* Model::parameterModel [private]
Definition at line 23 of file Model.h.
Referenced by buildParameterSet(), getParameterModel(), Model(), setModel(), setParameterModel(), successProbability(), and ~Model().
Author
Generated automatically by Doxygen for SICS IRT from the source code.