.TH "MultidimensionalModel" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MultidimensionalModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MultidimensionalModel\&.h>\fP
.PP
Inherits \fBDimensionModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultidimensionalModel\fP ()"
.br
.ti -1c
.RI "int \fBgetNumDimensions\fP ()"
.br
.ti -1c
.RI "vector< int > \fBgetDimVector\fP ()"
.br
.ti -1c
.RI "\fBLatentTraitSet\fP * \fBgetLatentTraitSet\fP () const "
.br
.ti -1c
.RI "void \fBsetLatentTraitSet\fP (\fBLatentTraitSet\fP *\fBlatentTraitSet\fP)"
.br
.ti -1c
.RI "virtual \fB~MultidimensionalModel\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file MultidimensionalModel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MultidimensionalModel::MultidimensionalModel ()"

.PP
Definition at line 10 of file MultidimensionalModel\&.cpp\&.
.SS "MultidimensionalModel::~MultidimensionalModel ()\fC [virtual]\fP"

.PP
Definition at line 18 of file MultidimensionalModel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "vector< int > MultidimensionalModel::getDimVector ()\fC [virtual]\fP"

.PP
Implements \fBDimensionModel\fP\&.
.PP
Definition at line 15 of file MultidimensionalModel\&.cpp\&.
.SS "\fBLatentTraitSet\fP * MultidimensionalModel::getLatentTraitSet () const\fC [virtual]\fP"

.PP
Implements \fBDimensionModel\fP\&.
.PP
Definition at line 22 of file MultidimensionalModel\&.cpp\&.
.PP
References DimensionModel::latentTraitSet\&.
.SS "int MultidimensionalModel::getNumDimensions ()\fC [virtual]\fP"

.PP
Implements \fBDimensionModel\fP\&.
.PP
Definition at line 31 of file MultidimensionalModel\&.cpp\&.
.SS "void MultidimensionalModel::setLatentTraitSet (\fBLatentTraitSet\fP * latentTraitSet)\fC [virtual]\fP"

.PP
Implements \fBDimensionModel\fP\&.
.PP
Definition at line 26 of file MultidimensionalModel\&.cpp\&.
.PP
References DimensionModel::latentTraitSet\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
