src/util/NCM.h
NAME
src/util/NCM.h -
SYNOPSIS
#include <type/Matrix.h>
#include <openblas/cblas.h>
#include <openblas/lapacke/lapacke.h>
#include <iostream>
#include <cstdio>
#include <cmath>
#include <ctime>
#include <cstdlib>
Classes
struct matrix
Macros
#define PERTURBATION 1.0e-9
Functions
void NCM (Matrix< double > *m)
void Correlation_Newton (struct matrix *G, struct matrix *X, double *y)
void pre_cg (double *b, double tol, int maxit, double *c, struct matrix *Omega12, struct matrix *P, double *p, int *flag, double *relres, int *iterk)
void precond_matrix (struct matrix *Omega12, struct matrix *P, double *c)
void gradient (double *y, double *lambda, struct matrix *P, double *b0, double *f, double *Fy)
void omega_mat (double *lambda, int n, struct matrix *Omega12)
void Jacobian_matrix (double *x, struct matrix *Omega12, struct matrix *P, struct matrix *Ax)
void printMatrix (struct matrix *M)
double max (double a, double b)
double norm (double *a, int n)
Macro Definition Documentation
#define PERTURBATION 1.0e-9
Definition at line 60 of file NCM.h.
Referenced by Jacobian_matrix().
Function Documentation
void Correlation_Newton (struct matrix * G, struct matrix * X, double * y)
Definition at line 264 of file NCM.h.
References a, b, c, matrix::columns, d, matrix::entries, gradient(), norm(), omega_mat(), pre_cg(), precond_matrix(), and matrix::rows.
Referenced by NCM().
void gradient (double * y, double * lambda, struct matrix * P, double * b0, double * f, double * Fy)
Definition at line 692 of file NCM.h.
References matrix::columns, matrix::entries, max(), and matrix::rows.
Referenced by Correlation_Newton(), and rosenbrockTest().
void Jacobian_matrix (double * x, struct matrix * Omega12, struct matrix * P, struct matrix * Ax)
Definition at line 747 of file NCM.h.
References matrix::columns, matrix::entries, PERTURBATION, and matrix::rows.
Referenced by pre_cg().
double max (double a, double b) [inline]
Definition at line 156 of file NCM.h.
Referenced by gradient().
void NCM (Matrix< double > * m)
Definition at line 134 of file NCM.h.
References matrix::columns, Correlation_Newton(), matrix::entries, Matrix< T >::nC(), Matrix< T >::nR(), and matrix::rows.
double norm (double * a, int n) [inline]
Definition at line 157 of file NCM.h.
Referenced by Correlation_Newton(), and pre_cg().
void omega_mat (double * lambda, int n, struct matrix * Omega12)
Definition at line 716 of file NCM.h.
References matrix::columns, matrix::entries, and matrix::rows.
Referenced by Correlation_Newton().
void pre_cg (double * b, double tol, int maxit, double * c, struct matrix * Omega12, struct matrix * P, double * p, int * flag, double * relres, int * iterk)
Definition at line 175 of file NCM.h.
References matrix::columns, d, matrix::entries, Jacobian_matrix(), norm(), and matrix::rows.
Referenced by Correlation_Newton().
void precond_matrix (struct matrix * Omega12, struct matrix * P, double * c)
Definition at line 602 of file NCM.h.
References matrix::columns, matrix::entries, and matrix::rows.
Referenced by Correlation_Newton().
void printMatrix (struct matrix * M)
Definition at line 165 of file NCM.h.
References matrix::columns, matrix::entries, and matrix::rows.
Author
Generated automatically by Doxygen for SICS IRT from the source code.