.TH "src/optimizer/NewtonOptimizer.h" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/optimizer/NewtonOptimizer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include <type/Matrix\&.h>\fP
.br
\fC#include <util/blasInterface\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
