.TH "Optimizer" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Optimizer \- Wrapper fot the other optimizers, take general functions for the function to optimize, the vector gradient function and the matrix hessian function The parameters are : double * args (Arguments over which the function optimizes) double * pars (Arguments in whose the function depends but are not optimized) int nargs Number of arguments int npars Number of parameters double * return (Return of the function is put in this array\&.)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Optimizer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsearchOptimal\fP (double(*functionPtr)(double *, double *, int, int), void(*gradientPtr)(double *, double *, int, int, double *), void(*HessianPtr)(double *, double *, int, int, double *), double *args, double *pars, int nargs, int npars)"
.br
.ti -1c
.RI "\fB~Optimizer\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wrapper fot the other optimizers, take general functions for the function to optimize, the vector gradient function and the matrix hessian function The parameters are : double * args (Arguments over which the function optimizes) double * pars (Arguments in whose the function depends but are not optimized) int nargs Number of arguments int npars Number of parameters double * return (Return of the function is put in this array\&.) 
.PP
Definition at line 24 of file Optimizer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Optimizer::~Optimizer ()"

.PP
Definition at line 12 of file Optimizer\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Optimizer::searchOptimal (double(*)(double *, double *, int, int) functionPtr, void(*)(double *, double *, int, int, double *) gradientPtr, void(*)(double *, double *, int, int, double *) HessianPtr, double * args, double * pars, int nargs, int npars)"

.PP
Definition at line 3 of file Optimizer\&.cpp\&.
.PP
Referenced by rosenbrockTest(), and EMEstimation::stepM()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
