.TH "src/optimizer/Optimizer.h" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/optimizer/Optimizer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <optimizer/NewtonOptimizer\&.h>\fP
.br
\fC#include <optimizer/FisherScoringOptimizer\&.h>\fP
.br
\fC#include <optimizer/BFGSOptimizer\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOptimizer\fP"
.br
.RI "\fIWrapper fot the other optimizers, take general functions for the function to optimize, the vector gradient function and the matrix hessian function The parameters are : double * args (Arguments over which the function optimizes) double * pars (Arguments in whose the function depends but are not optimized) int nargs Number of arguments int npars Number of parameters double * return (Return of the function is put in this array\&.) \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
