.TH "Output" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Output \- Skeleton for the output class TODO : CSV output TODO : JSON online output TODO : TeX output for reports\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Output\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOutput\fP ()"
.br
.ti -1c
.RI "virtual \fB~Output\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Skeleton for the output class TODO : CSV output TODO : JSON online output TODO : TeX output for reports\&. 
.PP
Definition at line 18 of file Output\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Output::Output ()"

.PP
Definition at line 10 of file Output\&.cpp\&.
.SS "Output::~Output ()\fC [virtual]\fP"

.PP
Definition at line 15 of file Output\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
