.TH "ParameterModel" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParameterModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ParameterModel\&.h>\fP
.PP
Inherited by \fBRaschModel\fP, \fBThreePLModel\fP, and \fBTwoPLModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBbuildParameterSet\fP (\fBItemModel\fP *, \fBDimensionModel\fP *)=0"
.br
.ti -1c
.RI "virtual void \fBsuccessProbability\fP (\fBDimensionModel\fP *)=0"
.br
.ti -1c
.RI "virtual map< \fBParameter\fP, \fBMatrix\fP< double > * > \fBgetParameterSet\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBsetParameterSet\fP (map< \fBParameter\fP, \fBMatrix\fP< double > * > \fBparameterSet\fP)=0"
.br
.ti -1c
.RI "virtual double \fBgetProbability\fP (int, int)=0"
.br
.ti -1c
.RI "virtual \fB~ParameterModel\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMatrix\fP< double > * \fBprobabilityMatrix\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "map< \fBParameter\fP, \fBMatrix\fP< double > * > \fBparameterSet\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file ParameterModel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParameterModel::~ParameterModel ()\fC [virtual]\fP"

.PP
Definition at line 10 of file ParameterModel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void ParameterModel::buildParameterSet (\fBItemModel\fP *, \fBDimensionModel\fP *)\fC [pure virtual]\fP"

.PP
Implemented in \fBThreePLModel\fP, \fBRaschModel\fP, and \fBTwoPLModel\fP\&.
.PP
Referenced by Model::buildParameterSet(), and oneRun()\&.
.SS "virtual map<\fBParameter\fP, \fBMatrix\fP<double> *> ParameterModel::getParameterSet ()\fC [pure virtual]\fP"

.PP
Implemented in \fBThreePLModel\fP, \fBRaschModel\fP, and \fBTwoPLModel\fP\&.
.PP
Referenced by EMEstimation::estimate(), oneRun(), EMEstimation::stepE(), and EMEstimation::stepM()\&.
.SS "virtual double ParameterModel::getProbability (int, int)\fC [pure virtual]\fP"

.PP
Implemented in \fBThreePLModel\fP, \fBRaschModel\fP, and \fBTwoPLModel\fP\&.
.PP
Referenced by EMEstimation::stepE()\&.
.SS "virtual void ParameterModel::setParameterSet (map< \fBParameter\fP, \fBMatrix\fP< double > * > parameterSet)\fC [pure virtual]\fP"

.PP
Implemented in \fBThreePLModel\fP, \fBRaschModel\fP, and \fBTwoPLModel\fP\&.
.PP
Referenced by EMEstimation::setInitialValues(), and EMEstimation::stepM()\&.
.SS "virtual void ParameterModel::successProbability (\fBDimensionModel\fP *)\fC [pure virtual]\fP"

.PP
Implemented in \fBThreePLModel\fP, \fBRaschModel\fP, and \fBTwoPLModel\fP\&.
.PP
Referenced by Model::successProbability()\&.
.SH "Member Data Documentation"
.PP 
.SS "map<\fBParameter\fP, \fBMatrix\fP<double> * > ParameterModel::parameterSet\fC [protected]\fP"

.PP
Definition at line 24 of file ParameterModel\&.h\&.
.PP
Referenced by ThreePLModel::buildParameterSet(), RaschModel::getParameterSet(), TwoPLModel::getParameterSet(), ThreePLModel::getParameterSet(), RaschModel::setParameterSet(), TwoPLModel::setParameterSet(), ThreePLModel::setParameterSet(), ThreePLModel::successProbability(), ThreePLModel::ThreePLModel(), and ThreePLModel::~ThreePLModel()\&.
.SS "\fBMatrix\fP<double>* ParameterModel::probabilityMatrix"

.PP
Definition at line 26 of file ParameterModel\&.h\&.
.PP
Referenced by ThreePLModel::buildParameterSet(), ThreePLModel::getProbability(), and ThreePLModel::ThreePLModel()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
