.TH "src/model/parameter/ParameterModel.h" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/model/parameter/ParameterModel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <type/Matrix\&.h>\fP
.br
\fC#include <model/item/ItemModel\&.h>\fP
.br
\fC#include <model/dimension/DimensionModel\&.h>\fP
.br
\fC#include <type/DataSet\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParameterModel\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBParameter\fP { \fBa\fP, \fBb\fP, \fBc\fP, \fBd\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBParameter\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIa \fP\fP
.TP
\fB\fIb \fP\fP
.TP
\fB\fIc \fP\fP
.TP
\fB\fId \fP\fP
.PP
Definition at line 19 of file ParameterModel\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
