ParameterModel
NAME
ParameterModel -
SYNOPSIS
#include <ParameterModel.h>
Inherited by RaschModel, ThreePLModel, and TwoPLModel.
Public Member Functions
virtual void buildParameterSet (ItemModel *, DimensionModel *)=0
virtual void successProbability (DimensionModel *)=0
virtual map< Parameter, Matrix< double > * > getParameterSet ()=0
virtual void setParameterSet (map< Parameter, Matrix< double > * > parameterSet)=0
virtual double getProbability (int, int)=0
virtual ~ParameterModel ()
Public Attributes
Matrix< double > * probabilityMatrix
Protected Attributes
map< Parameter, Matrix< double > * > parameterSet
Detailed Description
Definition at line 21 of file ParameterModel.h.
Constructor & Destructor Documentation
ParameterModel::~ParameterModel () [virtual]
Definition at line 10 of file ParameterModel.cpp.
Member Function Documentation
virtual void ParameterModel::buildParameterSet (ItemModel *, DimensionModel *) [pure virtual]
Implemented in ThreePLModel, RaschModel, and TwoPLModel.
Referenced by Model::buildParameterSet(), and oneRun().
virtual map<Parameter, Matrix<double> *> ParameterModel::getParameterSet () [pure virtual]
Implemented in ThreePLModel, RaschModel, and TwoPLModel.
Referenced by EMEstimation::estimate(), oneRun(), EMEstimation::stepE(), and EMEstimation::stepM().
virtual double ParameterModel::getProbability (int, int) [pure virtual]
Implemented in ThreePLModel, RaschModel, and TwoPLModel.
Referenced by EMEstimation::stepE().
virtual void ParameterModel::setParameterSet (map< Parameter, Matrix< double > * > parameterSet) [pure virtual]
Implemented in ThreePLModel, RaschModel, and TwoPLModel.
Referenced by EMEstimation::setInitialValues(), and EMEstimation::stepM().
virtual void ParameterModel::successProbability (DimensionModel *) [pure virtual]
Implemented in ThreePLModel, RaschModel, and TwoPLModel.
Referenced by Model::successProbability().
Member Data Documentation
map<Parameter, Matrix<double> * > ParameterModel::parameterSet [protected]
Definition at line 24 of file ParameterModel.h.
Referenced by ThreePLModel::buildParameterSet(), RaschModel::getParameterSet(), TwoPLModel::getParameterSet(), ThreePLModel::getParameterSet(), RaschModel::setParameterSet(), TwoPLModel::setParameterSet(), ThreePLModel::setParameterSet(), ThreePLModel::successProbability(), ThreePLModel::ThreePLModel(), and ThreePLModel::~ThreePLModel().
Matrix<double>* ParameterModel::probabilityMatrix
Definition at line 26 of file ParameterModel.h.
Referenced by ThreePLModel::buildParameterSet(), ThreePLModel::getProbability(), and ThreePLModel::ThreePLModel().
Author
Generated automatically by Doxygen for SICS IRT from the source code.