.TH "src/type/PatternMatrix.h" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/type/PatternMatrix.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/dynamic_bitset\&.hpp>\fP
.br
\fC#include <map>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <type/DataSet\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPatternMatrix\fP"
.br
.RI "\fIClass for holding binary matrices in the array of patterns of bitsets form\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
