PatternMatrix
NAME
PatternMatrix - Class for holding binary matrices in the array of patterns of bitsets form.
SYNOPSIS
#include <PatternMatrix.h>
Inherits DataSet.
Public Member Functions
PatternMatrix ()
void resetIterator ()
use this when reading in order
bool checkEnd ()
void iterate ()
void values ()
boost::dynamic_bitset getCurrentBitSet ()
long int getCurrentFrequency ()
void push (boost::dynamic_bitset<>)
void push (boost::dynamic_bitset<>, int)
Use this to fill the pattern matrix.
void flush ()
Use this to fill the pattern matrix many times with a pattern.
long int & operator() (boost::dynamic_bitset<>)
Use this to clean matrix.
int countItems () const
Output operator.
int countIndividuals () const
virtual ~PatternMatrix ()
Public Attributes
std::map< boost::dynamic_bitset<>, long int >::const_iterator iterator
Private Attributes
map< boost::dynamic_bitset<>, long int > matrix
Friends
std::ostream & operator<< (std::ostream &, PatternMatrix &)
Use this to access a specific pattern frecuency and modify it.
Detailed Description
Class for holding binary matrices in the array of patterns of bitsets form.
Definition at line 20 of file PatternMatrix.h.
Constructor & Destructor Documentation
PatternMatrix::PatternMatrix ()
Definition at line 10 of file PatternMatrix.cpp.
PatternMatrix::~PatternMatrix () [virtual]
Definition at line 32 of file PatternMatrix.cpp.
Member Function Documentation
bool PatternMatrix::checkEnd () [inline]
Definition at line 32 of file PatternMatrix.h.
Referenced by EMEstimation::stepE().
int PatternMatrix::countIndividuals () const [virtual]
Implements DataSet.
Definition at line 20 of file PatternMatrix.cpp.
int PatternMatrix::countItems () const [virtual]
Output operator.
Implements DataSet.
Definition at line 15 of file PatternMatrix.cpp.
Referenced by DichotomousModel::countItems(), and EMEstimation::stepE().
void PatternMatrix::flush ()
Use this to fill the pattern matrix many times with a pattern.
Definition at line 44 of file PatternMatrix.cpp.
boost::dynamic_bitset PatternMatrix::getCurrentBitSet () [inline]
Definition at line 35 of file PatternMatrix.h.
Referenced by EMEstimation::stepE().
long int PatternMatrix::getCurrentFrequency () [inline]
Definition at line 36 of file PatternMatrix.h.
Referenced by EMEstimation::stepE().
void PatternMatrix::iterate () [inline]
Definition at line 33 of file PatternMatrix.h.
Referenced by EMEstimation::stepE().
long int & PatternMatrix::operator() (boost::dynamic_bitset<> n)
Use this to clean matrix.
Definition at line 48 of file PatternMatrix.cpp.
void PatternMatrix::push (boost::dynamic_bitset<> n)
Definition at line 36 of file PatternMatrix.cpp.
Referenced by Input::importCSV().
void PatternMatrix::push (boost::dynamic_bitset<> n, int k)
Use this to fill the pattern matrix.
Definition at line 40 of file PatternMatrix.cpp.
void PatternMatrix::resetIterator () [inline]
use this when reading in order
Definition at line 31 of file PatternMatrix.h.
Referenced by EMEstimation::stepE().
void PatternMatrix::values () [inline]
Definition at line 34 of file PatternMatrix.h.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, PatternMatrix & pm) [friend]
Use this to access a specific pattern frecuency and modify it.
Definition at line 52 of file PatternMatrix.cpp.
Member Data Documentation
std::map<boost::dynamic_bitset<>, long int>::const_iterator PatternMatrix::iterator
Definition at line 30 of file PatternMatrix.h.
Referenced by operator<<().
map<boost::dynamic_bitset<>, long int> PatternMatrix::matrix [private]
Definition at line 23 of file PatternMatrix.h.
Referenced by operator<<().
Author
Generated automatically by Doxygen for SICS IRT from the source code.