.TH "PolytomousModel" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PolytomousModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PolytomousModel\&.h>\fP
.PP
Inherits \fBItemModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPolytomousModel\fP ()"
.br
.ti -1c
.RI "int \fBcountCategories\fP ()"
.br
.ti -1c
.RI "int \fBcountItems\fP ()"
.br
.ti -1c
.RI "\fBDataSet\fP * \fBgetDataset\fP ()"
.br
.ti -1c
.RI "void \fBsetDataset\fP (\fBDataSet\fP *dataset)"
.br
.ti -1c
.RI "virtual \fB~PolytomousModel\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file PolytomousModel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PolytomousModel::PolytomousModel ()"

.PP
Definition at line 10 of file PolytomousModel\&.cpp\&.
.SS "PolytomousModel::~PolytomousModel ()\fC [virtual]\fP"

.PP
Definition at line 31 of file PolytomousModel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int PolytomousModel::countCategories ()\fC [virtual]\fP"

.PP
Implements \fBItemModel\fP\&.
.PP
Definition at line 15 of file PolytomousModel\&.cpp\&.
.SS "int PolytomousModel::countItems ()\fC [virtual]\fP"

.PP
Implements \fBItemModel\fP\&.
.PP
Definition at line 27 of file PolytomousModel\&.cpp\&.
.SS "\fBDataSet\fP * PolytomousModel::getDataset ()\fC [virtual]\fP"

.PP
Implements \fBItemModel\fP\&.
.PP
Definition at line 19 of file PolytomousModel\&.cpp\&.
.PP
References ItemModel::dataSet\&.
.SS "void PolytomousModel::setDataset (\fBDataSet\fP * dataset)\fC [virtual]\fP"

.PP
Implements \fBItemModel\fP\&.
.PP
Definition at line 23 of file PolytomousModel\&.cpp\&.
.PP
References ItemModel::dataSet\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
