.TH "src/model/SICSGeneralModel.h" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/model/SICSGeneralModel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <model/ModelFactory\&.h>\fP
.br
\fC#include <model/parameter/ThreePLModel\&.h>\fP
.br
\fC#include <model/item/DichotomousModel\&.h>\fP
.br
\fC#include <model/dimension/UnidimensionalModel\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSICSGeneralModel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
