.TH "SICSGeneralModel" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SICSGeneralModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SICSGeneralModel\&.h>\fP
.PP
Inherits \fBModelFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSICSGeneralModel\fP ()"
.br
.ti -1c
.RI "\fBParameterModel\fP * \fBcreateParameterModel\fP ()"
.br
.ti -1c
.RI "\fBItemModel\fP * \fBcreateItemModel\fP ()"
.br
.ti -1c
.RI "\fBDimensionModel\fP * \fBcreateDimensionModel\fP ()"
.br
.ti -1c
.RI "virtual \fB~SICSGeneralModel\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file SICSGeneralModel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SICSGeneralModel::SICSGeneralModel ()"

.PP
Definition at line 10 of file SICSGeneralModel\&.cpp\&.
.SS "SICSGeneralModel::~SICSGeneralModel ()\fC [virtual]\fP"

.PP
Definition at line 30 of file SICSGeneralModel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDimensionModel\fP * SICSGeneralModel::createDimensionModel ()\fC [virtual]\fP"

.PP
Implements \fBModelFactory\fP\&.
.PP
Definition at line 25 of file SICSGeneralModel\&.cpp\&.
.SS "\fBItemModel\fP * SICSGeneralModel::createItemModel ()\fC [virtual]\fP"

.PP
Implements \fBModelFactory\fP\&.
.PP
Definition at line 20 of file SICSGeneralModel\&.cpp\&.
.SS "\fBParameterModel\fP * SICSGeneralModel::createParameterModel ()\fC [virtual]\fP"

.PP
Implements \fBModelFactory\fP\&.
.PP
Definition at line 15 of file SICSGeneralModel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
