ThreePLModel
NAME
ThreePLModel - Model for the 3pl model, uses parameters a d c.
SYNOPSIS
#include <ThreePLModel.h>
Inherits ParameterModel.
Public Member Functions
ThreePLModel ()
void buildParameterSet (ItemModel *, DimensionModel *)
void successProbability (DimensionModel *)
map< Parameter, Matrix< double > * > getParameterSet ()
void setParameterSet (map< Parameter, Matrix< double > * >)
double getProbability (int, int)
virtual ~ThreePLModel ()
Static Public Member Functions
static double successProbability (double, double, double, double)
static double successProbability_cPrime (double, double, double, double)
static double logLikelihood (double *, double *, int, int)
static void gradient (double *, double *, int, int, double *)
static void Ngradient (double *args, double *pars, int nargs, int npars, double *gradient)
static void Hessian (double *args, double *pars, int nargs, int npars, double *Hessian)
static void NHessian (double *args, double *pars, int nargs, int npars, double *Hessian)
static void itemHessian (double *args, double *pars, int nargs, int npars, double *Hessian)
static void itemgradient (double *, double *, int, int, double *)
In the item gradient and hessians these procedures take an already calculated hessian and gradient and just access the item that is needed in the optimization step args will then be the ith args for the item pars is going to be the full array of gradients and npars is going to be used to take the ith element the gradient will then be copied to g.
Additional Inherited Members
Detailed Description
Model for the 3pl model, uses parameters a d c.
unidimensional
Definition at line 25 of file ThreePLModel.h.
Constructor & Destructor Documentation
ThreePLModel::ThreePLModel ()
Definition at line 10 of file ThreePLModel.cpp.
References a, b, c, d, ParameterModel::parameterSet, and ParameterModel::probabilityMatrix.
ThreePLModel::~ThreePLModel () [virtual]
Definition at line 617 of file ThreePLModel.cpp.
References a, b, c, d, and ParameterModel::parameterSet.
Member Function Documentation
void ThreePLModel::buildParameterSet (ItemModel * itemModel, DimensionModel * dimensionModel) [virtual]
Implements ParameterModel.
Definition at line 20 of file ThreePLModel.cpp.
References a, c, ItemModel::countItems(), d, DimensionModel::getLatentTraitSet(), LatentTraitSet::getTheta(), Matrix< T >::nC(), ParameterModel::parameterSet, and ParameterModel::probabilityMatrix.
map< Parameter, Matrix< double > * > ThreePLModel::getParameterSet () [virtual]
Implements ParameterModel.
Definition at line 81 of file ThreePLModel.cpp.
References ParameterModel::parameterSet.
double ThreePLModel::getProbability (int node, int item) [virtual]
Implements ParameterModel.
Definition at line 111 of file ThreePLModel.cpp.
References ParameterModel::probabilityMatrix.
void ThreePLModel::gradient (double * args, double * pars, int nargs, int npars, double * gradient) [static]
Definition at line 378 of file ThreePLModel.cpp.
References a, b, c, Constant::NORM_CONST, and successProbability().
Referenced by NHessian(), and EMEstimation::stepM().
void ThreePLModel::Hessian (double * args, double * pars, int nargs, int npars, double * Hessian) [static]
Definition at line 139 of file ThreePLModel.cpp.
References a, b, c, Constant::NORM_CONST, and successProbability().
Referenced by EMEstimation::stepM().
void ThreePLModel::itemgradient (double * args, double * grad, int nargs, int i, double * tgrad) [static]
In the item gradient and hessians these procedures take an already calculated hessian and gradient and just access the item that is needed in the optimization step args will then be the ith args for the item pars is going to be the full array of gradients and npars is going to be used to take the ith element the gradient will then be copied to g.
Definition at line 129 of file ThreePLModel.cpp.
Referenced by EMEstimation::stepM().
void ThreePLModel::itemHessian (double * args, double * pars, int nargs, int npars, double * Hessian) [static]
Definition at line 115 of file ThreePLModel.cpp.
Referenced by EMEstimation::stepM().
double ThreePLModel::logLikelihood (double * args, double * pars, int nargs, int npars) [static]
Definition at line 510 of file ThreePLModel.cpp.
References a, b, c, and successProbability().
Referenced by Ngradient(), and EMEstimation::stepM().
void ThreePLModel::Ngradient (double * args, double * pars, int nargs, int npars, double * gradient) [static]
Definition at line 328 of file ThreePLModel.cpp.
References logLikelihood().
void ThreePLModel::NHessian (double * args, double * pars, int nargs, int npars, double * Hessian) [static]
Definition at line 341 of file ThreePLModel.cpp.
References gradient().
void ThreePLModel::setParameterSet (map< Parameter, Matrix< double > * > parameterSet) [virtual]
Implements ParameterModel.
Definition at line 85 of file ThreePLModel.cpp.
References ParameterModel::parameterSet.
double ThreePLModel::successProbability (double theta, double a, double d, double c) [static]
Definition at line 90 of file ThreePLModel.cpp.
References Constant::MAX_EXP, and Constant::NORM_CONST.
Referenced by gradient(), Hessian(), logLikelihood(), successProbability(), and successProbability_cPrime().
void ThreePLModel::successProbability (DimensionModel * dimensionModel) [virtual]
Implements ParameterModel.
Definition at line 52 of file ThreePLModel.cpp.
References a, c, d, DimensionModel::getLatentTraitSet(), LatentTraitSet::getTheta(), Matrix< T >::nC(), ParameterModel::parameterSet, and successProbability().
double ThreePLModel::successProbability_cPrime (double theta, double a, double b, double c) [static]
Definition at line 611 of file ThreePLModel.cpp.
References successProbability().
Author
Generated automatically by Doxygen for SICS IRT from the source code.