.TH "src/model/parameter/ThreePLModel.h" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/model/parameter/ThreePLModel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <typeinfo>\fP
.br
\fC#include <model/parameter/ParameterModel\&.h>\fP
.br
\fC#include <model/item/DichotomousModel\&.h>\fP
.br
\fC#include <model/item/PolytomousModel\&.h>\fP
.br
\fC#include <model/dimension/UnidimensionalModel\&.h>\fP
.br
\fC#include <model/dimension/MultidimensionalModel\&.h>\fP
.br
\fC#include <model/dimension/MultiUniDimModel\&.h>\fP
.br
\fC#include <type/PatternMatrix\&.h>\fP
.br
\fC#include <type/Constant\&.h>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBThreePLModel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
