.TH "Trace" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Trace \- \fBTrace\fP class for constructing execution and error logs onto files\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Trace\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrace\fP (const char *)"
.br
.ti -1c
.RI "template<typename T > void \fBoperator()\fP (\fBMatrix\fP< T > &)"
.br
.ti -1c
.RI "template<typename T > void \fBoperator()\fP (T)"
.br
.ti -1c
.RI "virtual \fB~Trace\fP ()"
.br
.ti -1c
.RI "const char * \fBgetFilename\fP () const "
.br
.ti -1c
.RI "void \fBsetFilename\fP (const char *\fBfilename\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const char * \fBfilename\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTrace\fP class for constructing execution and error logs onto files\&. 

Create a trace with a file to trace to that file when logging errors onto a trace the error logs onto the file asociated trace object can take ostreams, so any output class of cpp can output to the trace 
.PP
Definition at line 23 of file Trace\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Trace::Trace (const char * filename)"

.PP
Definition at line 10 of file Trace\&.cpp\&.
.PP
References filename\&.
.SS "Trace::~Trace ()\fC [virtual]\fP"

.PP
Definition at line 17 of file Trace\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "const char * Trace::getFilename () const"

.PP
Definition at line 21 of file Trace\&.cpp\&.
.PP
References filename\&.
.SS "template<typename T > void Trace::operator() (\fBMatrix\fP< T > & message)"

.PP
Definition at line 41 of file Trace\&.h\&.
.SS "template<typename T > void Trace::operator() (T message)"

.PP
Definition at line 52 of file Trace\&.h\&.
.SS "void Trace::setFilename (const char * filename)"

.PP
Definition at line 25 of file Trace\&.cpp\&.
.PP
References filename\&.
.SH "Member Data Documentation"
.PP 
.SS "const char* Trace::filename\fC [private]\fP"

.PP
Definition at line 24 of file Trace\&.h\&.
.PP
Referenced by getFilename(), setFilename(), and Trace()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
