.TH "TwoPLModel" 3 "Tue Sep 23 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TwoPLModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TwoPLModel\&.h>\fP
.PP
Inherits \fBParameterModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTwoPLModel\fP ()"
.br
.ti -1c
.RI "void \fBbuildParameterSet\fP (\fBItemModel\fP *, \fBDimensionModel\fP *)"
.br
.ti -1c
.RI "void \fBsuccessProbability\fP (\fBDimensionModel\fP *)"
.br
.ti -1c
.RI "map< \fBParameter\fP, \fBMatrix\fP< double > * > \fBgetParameterSet\fP ()"
.br
.ti -1c
.RI "void \fBsetParameterSet\fP (map< \fBParameter\fP, \fBMatrix\fP< double > * >)"
.br
.ti -1c
.RI "double \fBgetProbability\fP (int, int)"
.br
.ti -1c
.RI "virtual \fB~TwoPLModel\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file TwoPLModel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TwoPLModel::TwoPLModel ()"

.PP
Definition at line 10 of file TwoPLModel\&.cpp\&.
.SS "TwoPLModel::~TwoPLModel ()\fC [virtual]\fP"

.PP
Definition at line 33 of file TwoPLModel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void TwoPLModel::buildParameterSet (\fBItemModel\fP * itemModel, \fBDimensionModel\fP * dimensionModel)\fC [virtual]\fP"

.PP
Implements \fBParameterModel\fP\&.
.PP
Definition at line 15 of file TwoPLModel\&.cpp\&.
.SS "map< \fBParameter\fP, \fBMatrix\fP< double > * > TwoPLModel::getParameterSet ()\fC [virtual]\fP"

.PP
Implements \fBParameterModel\fP\&.
.PP
Definition at line 21 of file TwoPLModel\&.cpp\&.
.PP
References ParameterModel::parameterSet\&.
.SS "double TwoPLModel::getProbability (int node, int item)\fC [virtual]\fP"

.PP
Implements \fBParameterModel\fP\&.
.PP
Definition at line 29 of file TwoPLModel\&.cpp\&.
.SS "void TwoPLModel::setParameterSet (map< \fBParameter\fP, \fBMatrix\fP< double > * > pair)\fC [virtual]\fP"

.PP
Implements \fBParameterModel\fP\&.
.PP
Definition at line 25 of file TwoPLModel\&.cpp\&.
.PP
References ParameterModel::parameterSet\&.
.SS "void TwoPLModel::successProbability (\fBDimensionModel\fP * dimensionModel)\fC [virtual]\fP"

.PP
Implements \fBParameterModel\fP\&.
.PP
Definition at line 19 of file TwoPLModel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
