.TH "UnidimensionalModel" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnidimensionalModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UnidimensionalModel\&.h>\fP
.PP
Inherits \fBDimensionModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnidimensionalModel\fP ()"
.br
.ti -1c
.RI "int \fBgetNumDimensions\fP ()"
.br
.ti -1c
.RI "vector< int > \fBgetDimVector\fP ()"
.br
.ti -1c
.RI "\fBLatentTraitSet\fP * \fBgetLatentTraitSet\fP () const "
.br
.ti -1c
.RI "void \fBsetLatentTraitSet\fP (\fBLatentTraitSet\fP *\fBlatentTraitSet\fP)"
.br
.ti -1c
.RI "virtual \fB~UnidimensionalModel\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file UnidimensionalModel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnidimensionalModel::UnidimensionalModel ()"

.PP
Definition at line 10 of file UnidimensionalModel\&.cpp\&.
.PP
References DimensionModel::latentTraitSet\&.
.SS "UnidimensionalModel::~UnidimensionalModel ()\fC [virtual]\fP"

.PP
Definition at line 35 of file UnidimensionalModel\&.cpp\&.
.PP
References DimensionModel::latentTraitSet\&.
.SH "Member Function Documentation"
.PP 
.SS "vector< int > UnidimensionalModel::getDimVector ()\fC [virtual]\fP"

.PP
Implements \fBDimensionModel\fP\&.
.PP
Definition at line 18 of file UnidimensionalModel\&.cpp\&.
.PP
References LatentTraitSet::getTheta(), DimensionModel::latentTraitSet, and Matrix< T >::nC()\&.
.SS "\fBLatentTraitSet\fP * UnidimensionalModel::getLatentTraitSet () const\fC [virtual]\fP"

.PP
Implements \fBDimensionModel\fP\&.
.PP
Definition at line 27 of file UnidimensionalModel\&.cpp\&.
.PP
References DimensionModel::latentTraitSet\&.
.SS "int UnidimensionalModel::getNumDimensions ()\fC [virtual]\fP"

.PP
Implements \fBDimensionModel\fP\&.
.PP
Definition at line 14 of file UnidimensionalModel\&.cpp\&.
.SS "void UnidimensionalModel::setLatentTraitSet (\fBLatentTraitSet\fP * latentTraitSet)\fC [virtual]\fP"

.PP
Implements \fBDimensionModel\fP\&.
.PP
Definition at line 31 of file UnidimensionalModel\&.cpp\&.
.PP
References DimensionModel::latentTraitSet\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
