src/util/util.h
NAME
src/util/util.h -
SYNOPSIS
#include <util/asa111.hpp>
Functions
double randomd ()
Functions part one Includes the next functions StdDev_bin : Calculates the standard deviation for a binary vector.
long double stdDev_bin (int tsum, int tN)
long double stdDev_bin (int tsum, int tN, double avg)
double normalInverse (double point)
Function Documentation
double normalInverse (double point) [inline]
Definition at line 42 of file util.h.
References ppnd().
Referenced by EMEstimation::setInitialValues().
double randomd () [inline]
Functions part one Includes the next functions StdDev_bin : Calculates the standard deviation for a binary vector. Determinant3_3 : Calculates the determinant of a 3 by 3 , 2d matrix. logTransform : Transforms from the 0 to 1 scale to the real scale (read logit) ExpTransform : Transforms from the real scale to the 0 , 1 scale (read antilogit) PCheck : checks if a number is a probability, if it is one returns a very big probability, if its zero, a very small but not null.
Definition at line 22 of file util.h.
Referenced by EMEstimation::setInitialValues().
long double stdDev_bin (int tsum, int tN) [inline]
Definition at line 28 of file util.h.
Referenced by EMEstimation::setInitialValues().
long double stdDev_bin (int tsum, int tN, double avg) [inline]
Definition at line 36 of file util.h.
Author
Generated automatically by Doxygen for SICS IRT from the source code.