.TH "src/util/util.h" 3 "Thu Oct 16 2014" "Version 1.00" "SICS IRT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/util/util.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <util/asa111\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBrandomd\fP ()"
.br
.RI "\fIFunctions part one Includes the next functions StdDev_bin : Calculates the standard deviation for a binary vector\&. \fP"
.ti -1c
.RI "long double \fBstdDev_bin\fP (int tsum, int tN)"
.br
.ti -1c
.RI "long double \fBstdDev_bin\fP (int tsum, int tN, double avg)"
.br
.ti -1c
.RI "double \fBnormalInverse\fP (double point)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double normalInverse (double point)\fC [inline]\fP"

.PP
Definition at line 42 of file util\&.h\&.
.PP
References ppnd()\&.
.PP
Referenced by EMEstimation::setInitialValues()\&.
.SS "double randomd ()\fC [inline]\fP"

.PP
Functions part one Includes the next functions StdDev_bin : Calculates the standard deviation for a binary vector\&. Determinant3_3 : Calculates the determinant of a 3 by 3 , 2d matrix\&. logTransform : Transforms from the 0 to 1 scale to the real scale (read logit) ExpTransform : Transforms from the real scale to the 0 , 1 scale (read antilogit) PCheck : checks if a number is a probability, if it is one returns a very big probability, if its zero, a very small but not null\&. 
.PP
Definition at line 22 of file util\&.h\&.
.PP
Referenced by EMEstimation::setInitialValues()\&.
.SS "long double stdDev_bin (int tsum, int tN)\fC [inline]\fP"

.PP
Definition at line 28 of file util\&.h\&.
.PP
Referenced by EMEstimation::setInitialValues()\&.
.SS "long double stdDev_bin (int tsum, int tN, double avg)\fC [inline]\fP"

.PP
Definition at line 36 of file util\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SICS IRT from the source code\&.
